version: '3.8'

services:
  consul-server:
    image: hashicorp/consul:latest
    command: "agent -server -bootstrap"
  consul-agent1:
    image: hashicorp/consul:latest
    container_name: consul
    ports:
      - "8500:8500"
    command: "agent -join consul-server -client 0.0.0.0 -ui"
    links:
      - consul-server
    depends_on:
      - consul-server
  consul-agent2:
    image: hashicorp/consul:latest
    command: "agent -join consul-server -client 0.0.0.0"
    links:
      - consul-server
    depends_on:
      - consul-server

  postgres:
    container_name: journaling-app-postgres
    image: postgres:16.0
    environment:
      POSTGRES_DB: journaling-app-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      PGDATA: /data/journaling-app-db
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:latest
    container_name: journaling-app-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_cont:/data/db

  redis:
    image: redis:latest
    container_name: journaling-app-redis
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

  user_svc:
    image: munchkin0812/pad-lab1:user_svc
    container_name: user-service
    depends_on:
      - postgres
      - redis

  journal_svc:
    image: munchkin0812/pad-lab1:journal_svc
    container_name: journal-service
    depends_on:
      - mongodb
      - redis

  gateway:
    image: munchkin0812/pad-lab1:gateway
    container_name: gateway
    ports:
      - 5000:5000
    depends_on:
      - user_svc
      - journal_svc

volumes:
  postgres-db:
    driver: local
  redis-data:
    driver: local
  mongodb_data_cont:
    driver: local
