# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from journal_svc.pb import journal_svc_pb2 as journal__svc__pb2


class JournalServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterEntry = channel.unary_unary(
                '/proto.JournalService/RegisterEntry',
                request_serializer=journal__svc__pb2.RegisterEntryRequest.SerializeToString,
                response_deserializer=journal__svc__pb2.RegisterEntryResponse.FromString,
                )
        self.GetUserEntries = channel.unary_unary(
                '/proto.JournalService/GetUserEntries',
                request_serializer=journal__svc__pb2.GetUserEntriesRequest.SerializeToString,
                response_deserializer=journal__svc__pb2.GetUserEntriesResponse.FromString,
                )


class JournalServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterEntry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserEntries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JournalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterEntry,
                    request_deserializer=journal__svc__pb2.RegisterEntryRequest.FromString,
                    response_serializer=journal__svc__pb2.RegisterEntryResponse.SerializeToString,
            ),
            'GetUserEntries': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserEntries,
                    request_deserializer=journal__svc__pb2.GetUserEntriesRequest.FromString,
                    response_serializer=journal__svc__pb2.GetUserEntriesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.JournalService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class JournalService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.JournalService/RegisterEntry',
            journal__svc__pb2.RegisterEntryRequest.SerializeToString,
            journal__svc__pb2.RegisterEntryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUserEntries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.JournalService/GetUserEntries',
            journal__svc__pb2.GetUserEntriesRequest.SerializeToString,
            journal__svc__pb2.GetUserEntriesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
