# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_msg.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0euser_msg.proto\x12\x05proto\"*\n\x04User\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\",\n\x0fRegisterRequest\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.proto.User\"#\n\x10RegisterResponse\x12\x0f\n\x07message\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_msg_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USER']._serialized_start=25
  _globals['_USER']._serialized_end=67
  _globals['_REGISTERREQUEST']._serialized_start=69
  _globals['_REGISTERREQUEST']._serialized_end=113
  _globals['_REGISTERRESPONSE']._serialized_start=115
  _globals['_REGISTERRESPONSE']._serialized_end=150
# @@protoc_insertion_point(module_scope)
