# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_svc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import user_msg_pb2 as user__msg__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0euser_svc.proto\x12\x05proto\x1a\x0euser_msg.proto2N\n\x0bUserService\x12?\n\x0cRegisterUser\x12\x16.proto.RegisterRequest\x1a\x17.proto.RegisterResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_svc_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERSERVICE']._serialized_start=41
  _globals['_USERSERVICE']._serialized_end=119
# @@protoc_insertion_point(module_scope)
